/**
 * CRAFT CREATOR'S — Custom Photo Framing Studio
 * Seed Data: Frames, Categories, Services, Testimonials, FAQs
 */

// ─── Frame Categories ─────────────────────────────────────────────────────────
const FRAME_CATEGORIES = [
  { name: 'Wooden Frames', slug: 'wooden-frames', description: 'Classic warmth and natural beauty in premium wood finishes.', order: 1 },
  { name: 'Metal Frames', slug: 'metal-frames', description: 'Sleek, contemporary aluminium and steel frames for a modern look.', order: 2 },
  { name: 'Modern Frames', slug: 'modern-frames', description: 'Clean lines and minimalist designs for the contemporary home.', order: 3 },
  { name: 'Vintage Frames', slug: 'vintage-frames', description: 'Ornate designs that evoke nostalgia and timeless elegance.', order: 4 },
  { name: 'Premium Frames', slug: 'premium-frames', description: 'Our finest selection of handcrafted luxury frames.', order: 5 },
  { name: 'Floating Frames', slug: 'floating-frames', description: 'Gallery-style floating frames that make your photo appear suspended.', order: 6 },
  { name: 'Black Frames', slug: 'black-frames', description: 'Bold, classic black frames — timeless and versatile.', order: 7 },
  { name: 'White Frames', slug: 'white-frames', description: 'Clean and airy white frames, perfect for light interiors.', order: 8 },
  { name: 'Golden Frames', slug: 'golden-frames', description: 'Opulent gold-leaf and brass frames for a regal statement.', order: 9 },
  { name: 'Minimal Frames', slug: 'minimal-frames', description: 'Understated, slender profiles that let your photo shine.', order: 10 },
];

// ─── Frame Materials ──────────────────────────────────────────────────────────
const FRAME_MATERIALS = [
  { name: 'Solid Wood', description: 'Sustainably sourced hardwood — teak, oak, or walnut.', priceAdder: 0, order: 1 },
  { name: 'MDF Wood', description: 'Smooth, uniform medium-density fibreboard for painted finishes.', priceAdder: -500, order: 2 },
  { name: 'Aluminium', description: 'Lightweight anodised aluminium for a clean contemporary look.', priceAdder: 0, order: 3 },
  { name: 'Steel', description: 'Heavy-gauge steel with a brushed or matte finish.', priceAdder: 500, order: 4 },
  { name: 'Composite', description: 'High-density resin composite with ornate carved details.', priceAdder: 200, order: 5 },
];

// ─── Frame Colors ─────────────────────────────────────────────────────────────
const FRAME_COLORS = [
  { name: 'Matte Black', hex: '#1a1a1a', order: 1 },
  { name: 'Gloss White', hex: '#f5f5f5', order: 2 },
  { name: 'Natural Oak', hex: '#c8a97a', order: 3 },
  { name: 'Dark Walnut', hex: '#4a2e1a', order: 4 },
  { name: 'Antique Gold', hex: '#D4AF37', order: 5 },
  { name: 'Brushed Silver', hex: '#9e9e9e', order: 6 },
  { name: 'Cherry Red', hex: '#8b1a1a', order: 7 },
  { name: 'Espresso Brown', hex: '#3e1e0a', order: 8 },
  { name: 'Slate Grey', hex: '#4a4a5a', order: 9 },
  { name: 'Ivory White', hex: '#f0ead6', order: 10 },
];

// ─── Frame Sizes ──────────────────────────────────────────────────────────────
const FRAME_SIZES = [
  { label: '4×6', width: 4, height: 6, basePrice: 800, isCustom: false, order: 1 },
  { label: '5×7', width: 5, height: 7, basePrice: 1000, isCustom: false, order: 2 },
  { label: '8×10', width: 8, height: 10, basePrice: 1500, isCustom: false, order: 3 },
  { label: '10×12', width: 10, height: 12, basePrice: 1800, isCustom: false, order: 4 },
  { label: '12×18', width: 12, height: 18, basePrice: 2500, isCustom: false, order: 5 },
  { label: '16×20', width: 16, height: 20, basePrice: 3200, isCustom: false, order: 6 },
  { label: '16×24', width: 16, height: 24, basePrice: 3800, isCustom: false, order: 7 },
  { label: '20×24', width: 20, height: 24, basePrice: 4500, isCustom: false, order: 8 },
  { label: '24×36', width: 24, height: 36, basePrice: 6500, isCustom: false, order: 9 },
  { label: 'Custom Size', width: 0, height: 0, basePrice: 2000, isCustom: true, order: 10 },
];

// ─── Glass Options ────────────────────────────────────────────────────────────
const GLASS_OPTIONS = [
  { name: 'Standard Glass', description: 'Clear float glass — economical and durable.', price: 0, order: 1 },
  { name: 'Anti-Glare Glass', description: 'Reduces reflections for better viewing in bright rooms.', price: 1200, order: 2 },
  { name: 'UV-Protection Glass', description: 'Blocks 99% of UV rays to prevent photo fading.', price: 2500, order: 3 },
  { name: 'Museum Glass', description: 'Optically pure, near-invisible glass for premium displays.', price: 4500, order: 4 },
  { name: 'Acrylic (No Glass)', description: 'Lightweight shatter-resistant acrylic, ideal for large prints.', price: 800, order: 5 },
];

// ─── Mount Options ────────────────────────────────────────────────────────────
const MOUNT_OPTIONS = [
  { name: 'Without Mount', description: 'Photo fills the entire frame — bold and direct.', price: 0, order: 1 },
  { name: 'White Mount', description: 'Classic white acid-free mount board, 2" border.', price: 800, order: 2 },
  { name: 'Black Mount', description: 'Dramatic black mount board for high-contrast photos.', price: 800, order: 3 },
  { name: 'Cream Mount', description: 'Warm cream tone, ideal for vintage and portrait photos.', price: 800, order: 4 },
  { name: 'Double Mount', description: 'Two-layer mount for a premium gallery exhibition look.', price: 1500, order: 5 },
];

// ─── Frame Designs ────────────────────────────────────────────────────────────
const FRAME_DESIGNS = [
  // ── WOODEN FRAMES ──
  {
    name: 'Teak Classic',
    slug: 'teak-classic',
    description: 'A timeless solid teak frame with a natural grain finish. Hand-sanded to perfection and finished with a matte lacquer that highlights the wood\'s natural warmth. Suitable for family portraits, landscapes, and wedding photographs.',
    imageUrl: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&q=85',
    galleryImages: [
      'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=800&q=85',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=85',
    ],
    material: 'Solid Wood',
    colors: ['Natural Oak', 'Dark Walnut', 'Espresso Brown'],
    availableSizes: ['4×6', '5×7', '8×10', '12×18', '16×24', '24×36', 'Custom Size'],
    thickness: '2.5cm',
    basePrice: 2200,
    productionDays: 3,
    featured: true,
    bestseller: true,
    category: 'Wooden Frames',
  },
  {
    name: 'Oak Signature',
    slug: 'oak-signature',
    description: 'Premium solid oak frame with a smooth, satin finish. The wide profile (3cm) gives this frame a commanding presence on any wall. Available in natural and smoked oak finishes.',
    imageUrl: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=85',
    galleryImages: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=85',
    ],
    material: 'Solid Wood',
    colors: ['Natural Oak', 'Dark Walnut'],
    availableSizes: ['8×10', '12×18', '16×24', '24×36', 'Custom Size'],
    thickness: '3cm',
    basePrice: 2800,
    productionDays: 4,
    featured: true,
    bestseller: false,
    category: 'Wooden Frames',
  },
  {
    name: 'Walnut Heritage',
    slug: 'walnut-heritage',
    description: 'Richly grained American walnut frame that exudes warmth and sophistication. A bold choice for living rooms and studies. Each frame has a unique grain pattern.',
    imageUrl: 'https://images.unsplash.com/photo-1567016432779-094069958ea5?w=800&q=85',
    galleryImages: [],
    material: 'Solid Wood',
    colors: ['Dark Walnut', 'Espresso Brown'],
    availableSizes: ['8×10', '12×18', '16×20', '16×24', '24×36', 'Custom Size'],
    thickness: '2cm',
    basePrice: 3200,
    productionDays: 4,
    featured: false,
    bestseller: true,
    category: 'Wooden Frames',
  },
  {
    name: 'Pine Rustic',
    slug: 'pine-rustic',
    description: 'Distressed pine frame with a reclaimed wood aesthetic. Knots, grain variations, and subtle imperfections give each frame its unique character — perfect for vintage and rural photography.',
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=85',
    galleryImages: [],
    material: 'Solid Wood',
    colors: ['Natural Oak', 'Espresso Brown'],
    availableSizes: ['4×6', '5×7', '8×10', '12×18', '16×24', 'Custom Size'],
    thickness: '2.5cm',
    basePrice: 1800,
    productionDays: 3,
    featured: false,
    bestseller: false,
    category: 'Wooden Frames',
  },
  // ── METAL FRAMES ──
  {
    name: 'Metro Slim',
    slug: 'metro-slim',
    description: 'Ultra-thin anodised aluminium frame with a 1cm profile. The minimalist\'s choice — this frame virtually disappears, making your photo the sole focus. Available in matte black, brushed silver, and champagne gold.',
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=85',
    galleryImages: [
      'https://images.unsplash.com/photo-1499914485622-a88fac536970?w=800&q=85',
    ],
    material: 'Aluminium',
    colors: ['Matte Black', 'Brushed Silver', 'Antique Gold'],
    availableSizes: ['5×7', '8×10', '10×12', '12×18', '16×24', '24×36', 'Custom Size'],
    thickness: '1cm',
    basePrice: 2000,
    productionDays: 2,
    featured: true,
    bestseller: true,
    category: 'Metal Frames',
  },
  {
    name: 'Industrial Steel',
    slug: 'industrial-steel',
    description: 'Heavy brushed steel frame with a raw industrial aesthetic. The 2.5cm flat profile is perfect for architectural photography and urban landscapes.',
    imageUrl: 'https://images.unsplash.com/photo-1499914485622-a88fac536970?w=800&q=85',
    galleryImages: [],
    material: 'Steel',
    colors: ['Brushed Silver', 'Matte Black', 'Slate Grey'],
    availableSizes: ['8×10', '12×18', '16×24', '24×36', 'Custom Size'],
    thickness: '2.5cm',
    basePrice: 2800,
    productionDays: 3,
    featured: false,
    bestseller: false,
    category: 'Metal Frames',
  },
  {
    name: 'Brass Refined',
    slug: 'brass-refined',
    description: 'Solid brass frame with a hand-polished finish that develops a beautiful patina over time. A statement piece for premium art collections and galleries.',
    imageUrl: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=85',
    galleryImages: [],
    material: 'Steel',
    colors: ['Antique Gold'],
    availableSizes: ['5×7', '8×10', '12×18', '16×24', 'Custom Size'],
    thickness: '1.5cm',
    basePrice: 4200,
    productionDays: 5,
    featured: true,
    bestseller: false,
    category: 'Metal Frames',
  },
  // ── MODERN FRAMES ──
  {
    name: 'Pure White Gallery',
    slug: 'pure-white-gallery',
    description: 'Museum-inspired clean white frame with sharp, square edges. The 2cm profile perfectly balances bold and minimal. Ideal for contemporary interiors, nurseries, and bright spaces.',
    imageUrl: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=85',
    galleryImages: [
      'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800&q=85',
    ],
    material: 'MDF Wood',
    colors: ['Gloss White', 'Ivory White'],
    availableSizes: ['4×6', '5×7', '8×10', '12×18', '16×20', '16×24', '24×36', 'Custom Size'],
    thickness: '2cm',
    basePrice: 1500,
    productionDays: 2,
    featured: true,
    bestseller: true,
    category: 'Modern Frames',
  },
  {
    name: 'Shadow Box Modern',
    slug: 'shadow-box-modern',
    description: 'Deep-set shadow box frame that creates a stunning 3D depth effect. The recessed design works beautifully for canvas prints, 3D art, and thick prints. Available with or without lighting.',
    imageUrl: 'https://images.unsplash.com/photo-1596079890701-dd35e0a0d7fc?w=800&q=85',
    galleryImages: [],
    material: 'MDF Wood',
    colors: ['Matte Black', 'Gloss White', 'Natural Oak'],
    availableSizes: ['8×10', '12×18', '16×24', '24×36', 'Custom Size'],
    thickness: '4cm',
    basePrice: 3500,
    productionDays: 4,
    featured: false,
    bestseller: false,
    category: 'Modern Frames',
  },
  {
    name: 'Minimalist Oak',
    slug: 'minimalist-oak',
    description: 'Razor-thin oak veneer frame with a 0.8cm profile — barely there, but beautifully present. Best paired with museum glass for a gallery-standard presentation.',
    imageUrl: 'https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=800&q=85',
    galleryImages: [],
    material: 'Solid Wood',
    colors: ['Natural Oak'],
    availableSizes: ['5×7', '8×10', '12×18', '16×24', 'Custom Size'],
    thickness: '0.8cm',
    basePrice: 2200,
    productionDays: 3,
    featured: false,
    bestseller: false,
    category: 'Modern Frames',
  },
  // ── VINTAGE FRAMES ──
  {
    name: 'Baroque Gold',
    slug: 'baroque-gold',
    description: 'Ornate baroque-inspired frame with hand-carved resin flourishes and a deep antique gold leaf finish. Perfect for portraits, wedding photos, and cherished memories.',
    imageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=85',
    galleryImages: [
      'https://images.unsplash.com/photo-1616137984207-5c7a4b7ee0f1?w=800&q=85',
    ],
    material: 'Composite',
    colors: ['Antique Gold'],
    availableSizes: ['5×7', '8×10', '12×18', '16×24', 'Custom Size'],
    thickness: '4cm',
    basePrice: 3800,
    productionDays: 5,
    featured: true,
    bestseller: false,
    category: 'Vintage Frames',
  },
  {
    name: 'Victorian Silver',
    slug: 'victorian-silver',
    description: 'Exquisitely detailed Victorian-era inspired frame with intricate floral motifs, finished in aged silver. A stunning choice for formal portraits and heirloom photographs.',
    imageUrl: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800&q=85',
    galleryImages: [],
    material: 'Composite',
    colors: ['Brushed Silver'],
    availableSizes: ['5×7', '8×10', '12×18', '16×24', 'Custom Size'],
    thickness: '3.5cm',
    basePrice: 3500,
    productionDays: 5,
    featured: false,
    bestseller: false,
    category: 'Vintage Frames',
  },
  {
    name: 'Antique Mahogany',
    slug: 'antique-mahogany',
    description: 'Deep mahogany-stained wood frame with a slightly distressed finish and subtle rope-carved detailing. Evokes the warmth of a classic study or library.',
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&q=85',
    galleryImages: [],
    material: 'Solid Wood',
    colors: ['Espresso Brown', 'Cherry Red'],
    availableSizes: ['8×10', '12×18', '16×24', '24×36', 'Custom Size'],
    thickness: '3cm',
    basePrice: 2900,
    productionDays: 4,
    featured: false,
    bestseller: true,
    category: 'Vintage Frames',
  },
  // ── PREMIUM FRAMES ──
  {
    name: 'Luxe Ebony',
    slug: 'luxe-ebony',
    description: 'Our flagship premium frame. Crafted from dense African ebony with an ultra-smooth lacquered finish. The weight and finish speak of pure luxury. Comes with museum glass as standard.',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=85',
    galleryImages: [
      'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&q=85',
    ],
    material: 'Solid Wood',
    colors: ['Matte Black'],
    availableSizes: ['8×10', '12×18', '16×24', '24×36', 'Custom Size'],
    thickness: '2cm',
    basePrice: 6500,
    productionDays: 7,
    featured: true,
    bestseller: false,
    category: 'Premium Frames',
  },
  {
    name: 'Grand Imperial',
    slug: 'grand-imperial',
    description: 'A masterpiece of frame-making. Hand-carved composite frame with 24-karat gold leaf application, double museum mount, and UV-protection museum glass. For photographs that deserve to be preserved for generations.',
    imageUrl: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800&q=85',
    galleryImages: [],
    material: 'Composite',
    colors: ['Antique Gold'],
    availableSizes: ['8×10', '12×18', '16×24', '24×36', 'Custom Size'],
    thickness: '5cm',
    basePrice: 9500,
    productionDays: 10,
    featured: true,
    bestseller: false,
    category: 'Premium Frames',
  },
  {
    name: 'Platinum Edition',
    slug: 'platinum-edition',
    description: 'Ultra-premium anodised aluminium frame with a platinum-toned brushed finish. Features hidden hanging hardware, corner cushions, and arrives in our signature gift box.',
    imageUrl: 'https://images.unsplash.com/photo-1618220179428-22790b461013?w=800&q=85',
    galleryImages: [],
    material: 'Aluminium',
    colors: ['Brushed Silver'],
    availableSizes: ['8×10', '12×18', '16×24', '24×36', 'Custom Size'],
    thickness: '1.5cm',
    basePrice: 5500,
    productionDays: 5,
    featured: false,
    bestseller: false,
    category: 'Premium Frames',
  },
  // ── FLOATING FRAMES ──
  {
    name: 'Float Classic',
    slug: 'float-classic',
    description: 'Gallery-standard floating frame where the print appears to hover within a deep-set black frame. The 1cm gap around the photo creates a dramatic, exhibition-quality presentation.',
    imageUrl: 'https://images.unsplash.com/photo-1600607686527-6fb886090705?w=800&q=85',
    galleryImages: [
      'https://images.unsplash.com/photo-1612198790700-5b8eed0f3cdb?w=800&q=85',
    ],
    material: 'MDF Wood',
    colors: ['Matte Black', 'Gloss White', 'Natural Oak'],
    availableSizes: ['8×10', '12×18', '16×24', '24×36', 'Custom Size'],
    thickness: '2.5cm',
    basePrice: 2800,
    productionDays: 3,
    featured: true,
    bestseller: true,
    category: 'Floating Frames',
  },
  {
    name: 'Float Walnut',
    slug: 'float-walnut',
    description: 'Solid walnut floating frame with a warm natural finish. The recessed well holds your print 1.5cm from the back of the frame, creating a subtle shadow and beautiful depth.',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=85',
    galleryImages: [],
    material: 'Solid Wood',
    colors: ['Dark Walnut'],
    availableSizes: ['8×10', '12×18', '16×24', '24×36', 'Custom Size'],
    thickness: '2.5cm',
    basePrice: 3500,
    productionDays: 4,
    featured: false,
    bestseller: false,
    category: 'Floating Frames',
  },
  // ── BLACK FRAMES ──
  {
    name: 'Black Obsidian',
    slug: 'black-obsidian',
    description: 'A deep, gloss black lacquered frame with a mirror-like finish. Dramatic and powerful, this frame elevates any photo with a sense of gallery authority.',
    imageUrl: 'https://images.unsplash.com/photo-1589834390005-5d4d9a177d1d?w=800&q=85',
    galleryImages: [],
    material: 'MDF Wood',
    colors: ['Matte Black'],
    availableSizes: ['4×6', '5×7', '8×10', '12×18', '16×24', '24×36', 'Custom Size'],
    thickness: '2cm',
    basePrice: 1800,
    productionDays: 2,
    featured: true,
    bestseller: true,
    category: 'Black Frames',
  },
  {
    name: 'Matte Noir',
    slug: 'matte-noir',
    description: 'A velvety matte black frame with a soft, non-reflective surface. The flat matte finish pairs perfectly with high-contrast black and white photography.',
    imageUrl: 'https://images.unsplash.com/photo-1526827826797-7b1a30c4a16e?w=800&q=85',
    galleryImages: [],
    material: 'Aluminium',
    colors: ['Matte Black'],
    availableSizes: ['5×7', '8×10', '12×18', '16×24', '24×36', 'Custom Size'],
    thickness: '1.5cm',
    basePrice: 2200,
    productionDays: 2,
    featured: false,
    bestseller: false,
    category: 'Black Frames',
  },
  {
    name: 'Ebony Wide',
    slug: 'ebony-wide',
    description: 'A wide-profile (4cm) matte black frame that commands attention. Ideal for large prints in statement spaces like reception areas and corporate offices.',
    imageUrl: 'https://images.unsplash.com/photo-1631889993959-41b4e9c6c585?w=800&q=85',
    galleryImages: [],
    material: 'MDF Wood',
    colors: ['Matte Black'],
    availableSizes: ['12×18', '16×24', '24×36', 'Custom Size'],
    thickness: '4cm',
    basePrice: 2500,
    productionDays: 3,
    featured: false,
    bestseller: false,
    category: 'Black Frames',
  },
  // ── WHITE FRAMES ──
  {
    name: 'Blanc Slim',
    slug: 'blanc-slim',
    description: 'A crisp, slender white frame that adds elegance without distraction. Perfect for nurseries, bright Scandinavian-style interiors, and light botanical photography.',
    imageUrl: 'https://images.unsplash.com/photo-1589834390005-5d4d9a177d1d?w=800&q=85',
    galleryImages: [],
    material: 'MDF Wood',
    colors: ['Gloss White', 'Ivory White'],
    availableSizes: ['4×6', '5×7', '8×10', '12×18', '16×24', 'Custom Size'],
    thickness: '1.5cm',
    basePrice: 1500,
    productionDays: 2,
    featured: true,
    bestseller: true,
    category: 'White Frames',
  },
  {
    name: 'Pearl White',
    slug: 'pearl-white',
    description: 'A gorgeous semi-gloss pearl white frame with a subtle iridescent sheen. Wide 3cm profile adds drama while keeping the palette soft and elegant.',
    imageUrl: 'https://images.unsplash.com/photo-1556909190-bacf1954e0c7?w=800&q=85',
    galleryImages: [],
    material: 'Composite',
    colors: ['Gloss White', 'Ivory White'],
    availableSizes: ['8×10', '12×18', '16×24', '24×36', 'Custom Size'],
    thickness: '3cm',
    basePrice: 2200,
    productionDays: 3,
    featured: false,
    bestseller: false,
    category: 'White Frames',
  },
  // ── GOLDEN FRAMES ──
  {
    name: 'Regency Gold',
    slug: 'regency-gold',
    description: 'Opulent gold-leaf composite frame with elegant bead-and-reel detailing. A favourite for wedding portraits, family heirlooms, and formal event photography.',
    imageUrl: 'https://images.unsplash.com/photo-1568952433726-3896e3881c65?w=800&q=85',
    galleryImages: [
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=85',
    ],
    material: 'Composite',
    colors: ['Antique Gold'],
    availableSizes: ['5×7', '8×10', '12×18', '16×24', '24×36', 'Custom Size'],
    thickness: '3.5cm',
    basePrice: 3200,
    productionDays: 5,
    featured: true,
    bestseller: true,
    category: 'Golden Frames',
  },
  {
    name: 'Champagne Leaf',
    slug: 'champagne-leaf',
    description: 'A lighter, modern interpretation of the gold frame. Champagne-toned gold leaf over a slim 2cm profile for a contemporary luxury feel.',
    imageUrl: 'https://images.unsplash.com/photo-1596731498067-166039f3abc9?w=800&q=85',
    galleryImages: [],
    material: 'Composite',
    colors: ['Antique Gold'],
    availableSizes: ['5×7', '8×10', '12×18', '16×24', 'Custom Size'],
    thickness: '2cm',
    basePrice: 2800,
    productionDays: 4,
    featured: false,
    bestseller: false,
    category: 'Golden Frames',
  },
  // ── MINIMAL FRAMES ──
  {
    name: 'Hairline Black',
    slug: 'hairline-black',
    description: 'A barely-there hairline aluminium frame — just 0.5cm wide. Almost invisible, it creates the sensation of the photograph floating directly on the wall. Used in galleries worldwide.',
    imageUrl: 'https://images.unsplash.com/photo-1541123437800-1bb1317badc2?w=800&q=85',
    galleryImages: [],
    material: 'Aluminium',
    colors: ['Matte Black', 'Brushed Silver'],
    availableSizes: ['8×10', '12×18', '16×24', '24×36', 'Custom Size'],
    thickness: '0.5cm',
    basePrice: 2000,
    productionDays: 2,
    featured: true,
    bestseller: false,
    category: 'Minimal Frames',
  },
  {
    name: 'Gallery Mono',
    slug: 'gallery-mono',
    description: 'Inspired by the frames found in New York\'s most prestigious contemporary galleries. A perfectly square 1cm aluminium profile in a satin anodised finish.',
    imageUrl: 'https://images.unsplash.com/photo-1577083165633-14ebcdb0f658?w=800&q=85',
    galleryImages: [],
    material: 'Aluminium',
    colors: ['Matte Black', 'Brushed Silver', 'Antique Gold'],
    availableSizes: ['5×7', '8×10', '12×18', '16×24', '24×36', 'Custom Size'],
    thickness: '1cm',
    basePrice: 1800,
    productionDays: 2,
    featured: false,
    bestseller: true,
    category: 'Minimal Frames',
  },
  {
    name: 'Scandi Natural',
    slug: 'scandi-natural',
    description: 'Scandinavian-inspired thin ash wood frame. Light, airy, and modern — at home in any contemporary space. The 1.2cm profile in a bleached natural finish.',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=85',
    galleryImages: [],
    material: 'Solid Wood',
    colors: ['Natural Oak', 'Ivory White'],
    availableSizes: ['4×6', '5×7', '8×10', '12×18', '16×24', 'Custom Size'],
    thickness: '1.2cm',
    basePrice: 1900,
    productionDays: 3,
    featured: false,
    bestseller: false,
    category: 'Minimal Frames',
  },
  // A few more for variety
  {
    name: 'Cherry Blossom',
    slug: 'cherry-blossom',
    description: 'Solid cherry wood with a warm, pinkish-red tone unique to cherry hardwood. Ages beautifully to a deeper, richer hue over time.',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=85',
    galleryImages: [],
    material: 'Solid Wood',
    colors: ['Cherry Red'],
    availableSizes: ['5×7', '8×10', '12×18', '16×24', 'Custom Size'],
    thickness: '2cm',
    basePrice: 2600,
    productionDays: 4,
    featured: false,
    bestseller: false,
    category: 'Wooden Frames',
  },
  {
    name: 'Bamboo Zen',
    slug: 'bamboo-zen',
    description: 'Eco-friendly bamboo frame with a natural, sustainable appeal. Light and strong, with a subtly textured surface that brings nature into your home.',
    imageUrl: 'https://images.unsplash.com/photo-1493240814882-e7f96573b87c?w=800&q=85',
    galleryImages: [],
    material: 'Solid Wood',
    colors: ['Natural Oak'],
    availableSizes: ['4×6', '5×7', '8×10', '12×18', '16×24', 'Custom Size'],
    thickness: '1.5cm',
    basePrice: 1700,
    productionDays: 3,
    featured: false,
    bestseller: false,
    category: 'Wooden Frames',
  },
  {
    name: 'Steel Duo',
    slug: 'steel-duo',
    description: 'Two-tone steel frame with a contrasting inner lip — one side matte black, one side brushed silver. Contemporary and versatile, it works with both colour and monochrome photography.',
    imageUrl: 'https://images.unsplash.com/photo-1546768292-fb12f6c92568?w=800&q=85',
    galleryImages: [],
    material: 'Steel',
    colors: ['Matte Black', 'Brushed Silver'],
    availableSizes: ['8×10', '12×18', '16×24', '24×36', 'Custom Size'],
    thickness: '2cm',
    basePrice: 3000,
    productionDays: 3,
    featured: false,
    bestseller: false,
    category: 'Metal Frames',
  },
  {
    name: 'Rose Gold Slim',
    slug: 'rose-gold-slim',
    description: 'Anodised aluminium in a warm rose gold finish. Flatters portraits, fashion photography, and flower imagery. A perfect gift choice.',
    imageUrl: 'https://images.unsplash.com/photo-1532372576444-dda954194ad0?w=800&q=85',
    galleryImages: [],
    material: 'Aluminium',
    colors: ['Antique Gold'],
    availableSizes: ['4×6', '5×7', '8×10', '12×18', '16×24', 'Custom Size'],
    thickness: '1cm',
    basePrice: 2300,
    productionDays: 2,
    featured: false,
    bestseller: false,
    category: 'Metal Frames',
  },
  {
    name: 'Panoramic Black',
    slug: 'panoramic-black',
    description: 'Designed specifically for panoramic and wide-format photographs. An extra-wide matte black frame with a recessed inner lip that perfectly showcases landscape and cityscape panoramas.',
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=85',
    galleryImages: [],
    material: 'MDF Wood',
    colors: ['Matte Black'],
    availableSizes: ['12×18', '16×24', '24×36', 'Custom Size'],
    thickness: '3cm',
    basePrice: 3200,
    productionDays: 4,
    featured: false,
    bestseller: false,
    category: 'Black Frames',
  },
  {
    name: 'Cream Classic',
    slug: 'cream-classic',
    description: 'A soft cream-toned MDF frame with a subtle distressed edge. Pairs beautifully with sepia-toned, vintage-filtered, or floral photography for a cottagecore aesthetic.',
    imageUrl: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=800&q=85',
    galleryImages: [],
    material: 'MDF Wood',
    colors: ['Ivory White', 'Gloss White'],
    availableSizes: ['4×6', '5×7', '8×10', '12×18', '16×24', 'Custom Size'],
    thickness: '2cm',
    basePrice: 1600,
    productionDays: 2,
    featured: false,
    bestseller: true,
    category: 'White Frames',
  },
  {
    name: 'Gilded Heritage',
    slug: 'gilded-heritage',
    description: 'A wide, ornate heritage gold frame with raised floral and leaf details. Brings the grandeur of a classical art museum into your home.',
    imageUrl: 'https://images.unsplash.com/photo-1524230659092-07f99a75c013?w=800&q=85',
    galleryImages: [],
    material: 'Composite',
    colors: ['Antique Gold'],
    availableSizes: ['5×7', '8×10', '12×18', '16×24', '24×36', 'Custom Size'],
    thickness: '5cm',
    basePrice: 4500,
    productionDays: 6,
    featured: false,
    bestseller: false,
    category: 'Golden Frames',
  },
  {
    name: 'Graphite Pro',
    slug: 'graphite-pro',
    description: 'Sleek graphite-anodised aluminium frame. Professional and corporate aesthetic — a popular choice for office and hospitality installations.',
    imageUrl: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=85',
    galleryImages: [],
    material: 'Aluminium',
    colors: ['Slate Grey', 'Matte Black'],
    availableSizes: ['8×10', '12×18', '16×24', '24×36', 'Custom Size'],
    thickness: '1.5cm',
    basePrice: 2400,
    productionDays: 2,
    featured: false,
    bestseller: false,
    category: 'Modern Frames',
  },
  {
    name: 'Float Silver',
    slug: 'float-silver',
    description: 'Brushed silver aluminium floating frame. The reflective inner surface bounces light beautifully around your photo, giving it a luminous, airy quality.',
    imageUrl: 'https://images.unsplash.com/photo-1565874756968-34c81fc4edea?w=800&q=85',
    galleryImages: [],
    material: 'Aluminium',
    colors: ['Brushed Silver'],
    availableSizes: ['8×10', '12×18', '16×24', '24×36', 'Custom Size'],
    thickness: '2cm',
    basePrice: 3200,
    productionDays: 3,
    featured: false,
    bestseller: false,
    category: 'Floating Frames',
  },
];

// ─── Services ─────────────────────────────────────────────────────────────────
const SERVICES = [
  {
    title: 'Photo Framing',
    slug: 'photo-framing',
    description: 'Our core service. We professionally frame your personal photographs — printed or digital — using premium materials and museum-standard techniques.',
    overview: 'Whether you want to display a cherished family portrait, a breathtaking travel photo, or a precious memory, our expert framers will create the perfect presentation. We handle everything from matting and mounting to glass selection and hanging hardware.',
    includes: ['Free size consultation', 'Acid-free mounting', 'Custom mat cutting', 'Professional hanging hardware', 'Protective glass or acrylic', 'Certificate of framing'],
    startingPrice: 1500,
    duration: '2–4 working days',
    featured: true,
    faqs: [
      { question: 'Can I bring a physical photo to frame?', answer: 'Absolutely. You can bring any printed photograph — any size, any finish — directly to our studio.' },
      { question: 'Can I upload a digital photo for printing and framing?', answer: 'Yes. Upload your digital image and we\'ll handle professional printing in-house before framing.' },
      { question: 'What sizes do you frame?', answer: 'We frame everything from small 4×6 keepsakes to large 24×36 statement pieces. Custom sizes are also available.' },
    ],
    order: 1,
  },
  {
    title: 'Canvas Framing',
    slug: 'canvas-framing',
    description: 'Transform your photograph into a stunning canvas print, gallery-stretched over a premium kiln-dried pine stretcher bar and framed to perfection.',
    overview: 'Canvas printing adds texture, warmth, and depth to your photograph. Our canvas prints are produced on fine-art cotton-polyester canvas using archival inks. We offer gallery wrap, floating frame, or traditional framing options.',
    includes: ['Premium canvas printing', 'Gallery stretching', 'Frame of choice', 'Hanging hardware', '100-year archival quality'],
    startingPrice: 3500,
    duration: '4–6 working days',
    featured: true,
    faqs: [
      { question: 'What is the difference between a canvas print and a regular photo print?', answer: 'Canvas gives a painterly texture and is typically displayed without glass, while photo prints require glass protection.' },
      { question: 'Can I get a gallery wrap without a frame?', answer: 'Yes, gallery wrap stretching is available as a standalone service without an outer frame.' },
    ],
    order: 2,
  },
  {
    title: 'Certificate Framing',
    slug: 'certificate-framing',
    description: 'Professional framing for certificates, degrees, awards, and diplomas. Preserve your achievements with archival-quality materials.',
    overview: 'Your academic or professional achievements deserve to be displayed with pride. We use acid-free materials throughout to prevent yellowing and degradation of your documents.',
    includes: ['Acid-free mounting', 'Custom mat cutting', 'Anti-UV glass', 'Hanging hardware', 'Document-safe adhesives'],
    startingPrice: 1800,
    duration: '2–3 working days',
    featured: false,
    faqs: [
      { question: 'Will framing damage my certificate?', answer: 'No. We use reversible, document-safe adhesives and acid-free materials that will not damage your document.' },
      { question: 'Can you frame oversized certificates?', answer: 'Yes, we handle all standard and non-standard document sizes.' },
    ],
    order: 3,
  },
  {
    title: 'Artwork Framing',
    slug: 'artwork-framing',
    description: 'Expert framing for original paintings, prints, and fine art. We use museum-standard conservation framing techniques.',
    overview: 'Framing original artwork requires specialist knowledge. We offer conservation and preservation framing that protects your artwork for generations, using archival materials and UV-protection glazing.',
    includes: ['Conservation assessment', 'Acid-free backboard', 'UV-protection glass', 'Museum-quality mounting', 'Archival tape', 'Certificate of conservation'],
    startingPrice: 4500,
    duration: '5–7 working days',
    featured: false,
    faqs: [
      { question: 'Do you frame original oil paintings?', answer: 'Yes, we can source or create custom frames for original oils and acrylics, including deep-set frames for thick canvas.' },
    ],
    order: 4,
  },
  {
    title: 'Poster Framing',
    slug: 'poster-framing',
    description: 'Quick, affordable framing for posters, prints, and limited-edition art prints. Standard and custom sizes available.',
    overview: 'Give your posters and prints the presentation they deserve. We offer a wide range of standard poster frames plus custom sizing for unusual dimensions.',
    includes: ['Standard or custom sizing', 'Protective glass or acrylic', 'Hanging hardware', 'Quick turnaround'],
    startingPrice: 800,
    duration: '1–2 working days',
    featured: true,
    faqs: [
      { question: 'Do you do same-day framing for posters?', answer: 'For standard sizes, same-day service may be available — call us to check availability.' },
    ],
    order: 5,
  },
  {
    title: 'Mirror Framing',
    slug: 'mirror-framing',
    description: 'Custom frame installation for mirrors. Transform a plain mirror into a statement piece with a beautiful custom frame.',
    overview: 'We can frame new mirrors or reframe existing ones. Choose from our extensive range of frame styles to create a custom framed mirror that becomes a focal point of any room.',
    includes: ['Mirror safety backing', 'Secure frame bonding', 'Wall mounting hardware', 'Size consultation'],
    startingPrice: 3500,
    duration: '5–7 working days',
    featured: false,
    faqs: [
      { question: 'Can you frame my existing mirror?', answer: 'Yes, bring your mirror to our studio and we\'ll create a custom frame to fit it.' },
    ],
    order: 6,
  },
  {
    title: 'Custom Frame Design',
    slug: 'custom-frame-design',
    description: 'Bespoke frame design from scratch. For clients who need something completely unique that cannot be found in our existing collection.',
    overview: 'Work directly with our master framers to design a completely custom frame. We can match existing décor, create painted finishes in any colour, or build frames to unusual shapes and dimensions.',
    includes: ['Personal consultation', 'Material sampling', 'Custom colour matching', 'Prototype approval', 'Full production'],
    startingPrice: 8000,
    duration: '10–14 working days',
    featured: false,
    faqs: [
      { question: 'Can you match a frame to my existing furniture?', answer: 'Yes. Bring a sample or photos of your furniture and we\'ll create a colour-matched frame.' },
    ],
    order: 7,
  },
  {
    title: 'Glass Replacement',
    slug: 'glass-replacement',
    description: 'Replace broken, scratched, or yellowed glass in your existing frames. Fast turnaround, same-day for standard sizes.',
    overview: 'Broken or deteriorated glass doesn\'t mean you need a new frame. We can replace the glass in almost any existing frame with standard or premium options including anti-glare and UV-protection glass.',
    includes: ['Frame inspection', 'Old glass removal', 'New glass cutting & fitting', 'Resealing'],
    startingPrice: 500,
    duration: '1–2 working days',
    featured: false,
    faqs: [
      { question: 'Can you replace with UV glass?', answer: 'Yes, we offer standard, anti-glare, and UV-protection glass replacements.' },
    ],
    order: 8,
  },
  {
    title: 'Frame Repair',
    slug: 'frame-repair',
    description: 'Expert repair for damaged, broken, or deteriorating frames. We restore frames to their original condition using specialist techniques.',
    overview: 'Family heirloom frames, antique frames, or simply damaged frames can often be restored rather than replaced. Our restoration specialists can repair broken joints, re-gild gold frames, touch up paint, and more.',
    includes: ['Damage assessment', 'Joint repair & regluing', 'Paint touch-up', 'Gold leaf restoration', 'Re-backing', 'Cleaning'],
    startingPrice: 700,
    duration: '3–5 working days',
    featured: false,
    faqs: [
      { question: 'Can you restore a very old antique frame?', answer: 'Yes. We specialise in the careful restoration of antique and heirloom frames using period-appropriate techniques.' },
    ],
    order: 9,
  },
  {
    title: 'Bulk Orders',
    slug: 'bulk-orders',
    description: 'Volume framing services for hotels, restaurants, offices, galleries, and corporate clients. Consistent quality at competitive pricing.',
    overview: 'We work with interior designers, hospitality groups, corporate clients, and galleries to deliver large-volume framing projects on time and on budget. Minimum order: 10 frames.',
    includes: ['Dedicated account manager', 'Site survey available', 'Consistent quality guarantee', 'Volume pricing', 'Coordinated delivery', 'Installation available'],
    startingPrice: 0,
    duration: 'Project-dependent',
    featured: true,
    faqs: [
      { question: 'What is the minimum order for bulk pricing?', answer: 'We offer bulk pricing for orders of 10 or more frames.' },
      { question: 'Do you offer installation services?', answer: 'Yes, for large projects we can arrange professional installation at your premises.' },
    ],
    order: 10,
  },
];

// ─── Testimonials ─────────────────────────────────────────────────────────────
const TESTIMONIALS = [
  {
    name: 'Priya Sharma',
    title: 'Interior Designer, Delhi',
    quote: 'Craft Creator\'s is my go-to for every client project. The quality is consistently outstanding — the Teak Classic frame transformed a simple holiday photo into a piece of art that anchors my client\'s entire living room.',
    rating: 5,
    featured: true,
  },
  {
    name: 'Rohan Mehta',
    title: 'Wedding Client, Mumbai',
    quote: 'We had our wedding portraits framed in the Grand Imperial and the result brought my mother to tears. The craftsmanship is extraordinary — you can feel the quality the moment you hold it.',
    rating: 5,
    featured: true,
  },
  {
    name: 'James Harlow',
    title: 'Architect, Bengaluru',
    quote: 'I ordered the Metro Slim frames for my entire home office wall — 12 frames in total. Every single one was perfect. Consistent, precise, and beautifully packaged. Outstanding service.',
    rating: 5,
    featured: false,
  },
  {
    name: 'Meera Nair',
    title: 'Photographer, Kochi',
    quote: 'As a professional photographer, I need frames that do justice to my work. Craft Creator\'s Float Classic is the only floating frame I trust. My clients are always blown away.',
    rating: 5,
    featured: true,
  },
  {
    name: 'Arjun Kapoor',
    title: 'Collector, Mumbai',
    quote: 'The Luxe Ebony frame for my fine art print is absolutely stunning. The weight, the finish, the precision of the corners — it rivals frames I\'ve seen in London and New York galleries.',
    rating: 5,
    featured: false,
  },
  {
    name: 'Ananya Reddy',
    title: 'Gift Buyer, Hyderabad',
    quote: 'I ordered a framed photo as a 25th anniversary gift for my parents. The team helped me choose the perfect Baroque Gold frame. My parents were overwhelmed. Will order again.',
    rating: 5,
    featured: false,
  },
  {
    name: 'Siddharth Rao',
    title: 'Restaurant Owner, Goa',
    quote: 'We ordered 40 frames for our new restaurant — a mix of styles and sizes. Every frame arrived on time, perfectly consistent, and looks incredible on our walls. Bulk service is exceptional.',
    rating: 5,
    featured: false,
  },
  {
    name: 'Kavya Krishnan',
    title: 'Corporate Client, Chennai',
    quote: 'Our office now has 25 beautiful framed prints from Craft Creator\'s. Professional, punctual, and the quality is premium. Our team and clients love the new look.',
    rating: 5,
    featured: false,
  },
  {
    name: 'Vikram Patel',
    title: 'Art Collector, Ahmedabad',
    quote: 'I brought a 100-year-old family portrait for restoration and re-framing. The care and respect the team showed for this irreplaceable piece was remarkable. The result is museum quality.',
    rating: 5,
    featured: true,
  },
  {
    name: 'Sunita Malhotra',
    title: 'Homemaker, Pune',
    quote: 'The WhatsApp ordering process is so easy! I uploaded my photo, chose my frame through the website, messaged them, and had a beautiful framed print in 3 days. Absolutely love it.',
    rating: 5,
    featured: false,
  },
];

// ─── FAQs ─────────────────────────────────────────────────────────────────────
const FAQS = [
  {
    category: 'General',
    question: 'How long does framing take?',
    answer: 'Standard orders are ready in 2–4 working days. Premium and custom frames may take 5–10 days. We\'ll confirm the exact timeline when you place your order.'
  },
  {
    category: 'Photo Upload',
    question: 'Can I upload a digital photo to be printed and framed?',
    answer: 'Yes! Upload your digital photo (JPG, PNG, JPEG, WEBP, or HEIC) using our online configurator. We print it professionally in-house before framing. We recommend a minimum resolution of 300 DPI for the size you want to print.'
  },
  {
    category: 'Photo Upload',
    question: 'What formats can I upload?',
    answer: 'We accept JPG, JPEG, PNG, WEBP, and HEIC formats. Maximum file size is 15MB. For best results, upload the highest resolution image you have.'
  },
  {
    category: 'Printed Photos',
    question: 'Can I bring a physical/printed photo?',
    answer: 'Absolutely. Simply bring your printed photo to our studio, or select "I will bring a printed copy" in the online configurator and we\'ll discuss the details via WhatsApp.'
  },
  {
    category: 'Sizing',
    question: 'Do you do custom sizes?',
    answer: 'Yes! Select "Custom Size" in the frame configurator and enter your exact dimensions in inches. We can frame almost any size. Custom sizes may add ₹500–₹2,000 to the base price depending on complexity.'
  },
  {
    category: 'Materials',
    question: 'What frame materials do you use?',
    answer: 'We work with solid wood (teak, oak, walnut, cherry, bamboo), high-quality MDF with premium finishes, anodised aluminium, brushed steel, and composite resin for ornate designs.'
  },
  {
    category: 'Glass',
    question: 'What glass options are available?',
    answer: 'We offer Standard Glass (clear), Anti-Glare Glass (reduces reflections), UV-Protection Glass (prevents photo fading), Museum Glass (premium, near-invisible), and Acrylic (lightweight, shatter-resistant). Anti-glare and UV options are highly recommended.'
  },
  {
    category: 'Pricing',
    question: 'How is the price calculated?',
    answer: 'Price depends on: the frame design you choose, the size of the frame, glass option, mount option, and quantity. Use our Live Price Calculator in the configurator to see an instant estimate.'
  },
  {
    category: 'Pricing',
    question: 'Do you offer bulk discounts?',
    answer: 'Yes! For orders of 10 or more frames, we offer volume pricing. Contact us via WhatsApp or our bulk orders page for a custom quotation.'
  },
  {
    category: 'Order',
    question: 'How do I place an order?',
    answer: 'Use our online configurator to select your frame, size, glass, and mount options. Upload your photo or indicate you\'ll bring a printed copy. Then click "Order via WhatsApp" — we\'ll confirm your order, provide a final quote, and arrange pickup or delivery.'
  },
  {
    category: 'Order',
    question: 'Do you have an online payment system?',
    answer: 'We don\'t take online payments — all orders are confirmed and paid directly through WhatsApp or in our studio. This allows us to ensure everything is perfect before you pay.'
  },
  {
    category: 'Delivery',
    question: 'Do you offer delivery?',
    answer: 'Yes, we offer home delivery within Mumbai. For customers outside Mumbai, we ship nationally via secure, padded courier. Shipping costs are calculated at the time of order.'
  },
];

module.exports = {
  FRAME_CATEGORIES,
  FRAME_MATERIALS,
  FRAME_COLORS,
  FRAME_SIZES,
  GLASS_OPTIONS,
  MOUNT_OPTIONS,
  FRAME_DESIGNS,
  SERVICES,
  TESTIMONIALS,
  FAQS,
};
